name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this Release
            
            - Updated VFS fonts for pdfmake
            - Added support for multiple languages
            - Improved font loading and registration
            
            ## Usage
            
            ### CDN
            ```html
            <script src="https://cdn.jsdelivr.net/gh/${{ github.repository }}@${{ github.ref_name }}/vfs_fonts-base.js"></script>
            ```
            
            ### NPM
            ```bash
            npm install pdfmake-font-vfs@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
